/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ./public/untitled-v1.glb --transform 
Files: ./public/untitled-v1.glb [585.02KB] > C:\Users\froxy\Downloads\portfolio2\untitled-v1-transformed.glb [32.78KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/untitled-v1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Apol001.geometry} material={materials.skin} rotation={[-1.105, -0.409, -0.698]} scale={[0.522, 0.811, 0.85]} />
    </group>
  )
}

useGLTF.preload('/untitled-v1-transformed.glb')
